[project]
name = "comfyui-v-express"
description = "[Original] In the field of portrait video generation, the use of single images to generate portrait videos has become increasingly prevalent. A common approach involves leveraging generative models to enhance adapters for controlled generation. However, control signals can vary in strength, including text, audio, image reference, pose, depth map, etc. Among these, weaker conditions often struggle to be effective due to interference from stronger conditions, posing a challenge in balancing these conditions. In our work on portrait video generation, we identified audio signals as particularly weak, often overshadowed by stronger signals such as pose and original image. However, direct training with weak signals often leads to difficulties in convergence. To address this, we propose V-Express, a simple method that balances different control signals through a series of progressive drop operations. Our method gradually enables effective control by weak conditions, thereby achieving generation capabilities that simultaneously take into account pose, input image, and audio.\nNOTE: You need to downdload [a/model_ckpts](https://huggingface.co/tk93/V-Express/tree/main) manually."
version = "1.0.0"
license = "LICENSE"
dependencies = ["diffusers==0.24.0", "imageio-ffmpeg==0.4.9", "insightface==0.7.3", "omegaconf==2.2.3", "onnxruntime==1.16.3", "safetensors==0.4.2", "torch==2.0.1", "torchaudio==2.0.2", "torchvision==0.15.2", "transformers==4.30.2", "einops==0.4.1", "tqdm==4.66.1", "xformers==0.0.22", "av==11.0.0"]

[project.urls]
Repository = "https://github.com/tiankuan93/ComfyUI-V-Express"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "ComfyUI-V-Express"
Icon = ""
